apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    app.kubernetes.io/name: {{ include "s3.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: s3
data:
  S3_SERVER_PORT: "{{ .Values.port }}"
  HEALTHCHECK_PATH: "{{ .Values.healthcheckPath }}"
  MAX_UPLOAD_SIZE_MB: "{{ .Values.maxUploadSizeMb }}"
  S3_BUCKET: "legi-bit-uploads"
  AWS_REGION: "eu-north-1"
