apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ include "s3.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: s3
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "s3.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: s3
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
