apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: legibit
  labels:
    app: legibit
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legibit
      component: web
  template:
    metadata:
      labels:
        app: legibit
        component: web
    spec:
      containers:
        - name: web
          image: webserver0518/legi-bit-nginx:v0.3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: web-config
            #- secretRef:
            #    name: web-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      restartPolicy: Always
