apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { .Values.ingress.name } }
  labels:
    app: { { include "legi-bit.name" . } }
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/load-balancer-name: legibit-alb

    alb.ingress.kubernetes.io/security-groups: sg-009b4bd9f3d3de562
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"

    alb.ingress.kubernetes.io/subnets: '{{ join "," .Values.network.publicSubnets }}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn:
      { { .Values.ingress.acmCertificateArn } }

    alb.ingress.kubernetes.io/ssl-redirect: "443"

    alb.ingress.kubernetes.io/healthcheck-path: /alb-health
    alb.ingress.kubernetes.io/success-codes: "200-399"
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port

    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10

    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=120,access_logs.s3.enabled=true,access_logs.s3.bucket=legi-bit-alb-logs,access_logs.s3.prefix=alb"

spec:
  ingressClassName: "alb"
  rules:
    - host: { { .Values.global.domain } }
      http:
        paths:
          # 1. Health check (HTTP only, no redirect)
          - path: /alb-health
            pathType: Exact
            backend:
              service:
                name: { { .Values.web.serviceName } }
                port:
                  number: { { .Values.web.service.port } }

          # 3. HTTPS â†’ web
          - path: /
            pathType: Prefix
            backend:
              service:
                name: { { .Values.web.serviceName } }
                port:
                  number: { { .Values.web.service.port } }

    - host: { { .Values.global.wwwdomain } }
      http:
        paths:
          - path: /alb-health
            pathType: Exact
            backend:
              service:
                name: { { .Values.web.serviceName } }
                port:
                  number: { { .Values.web.service.port } }

          - path: /
            pathType: Prefix
            backend:
              service:
                name: { { .Values.web.serviceName } }
                port:
                  number: { { .Values.web.service.port } }
