apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: {{ include "legi-bit.name" . }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "legi-bit.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "legi-bit.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.configMapName }}
            #- secretRef:
            #    name: backend-secret
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
      restartPolicy: Always
