apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceSES.configMapName }}
  labels:
    app: {{ include "legi-bit.name" . }}
    component: service-ses
data:
  S3_SERVER_PORT: "{{ .Values.serviceSES.port }}"
  HEALTHCHECK_PATH: "{{ .Values.serviceSES.healthcheckPath }}"
  MAX_UPLOAD_SIZE_MB: "{{ .Values.serviceSES.maxUploadSizeMb }}"