apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceMongodb.configMapName }}
  labels:
    app: {{ include "legi-bit.name" . }}
    component: service-mongodb
data:
  MONGODB_SERVER_PORT: "{{ .Values.serviceMongodb.port }}"
  HEALTHCHECK_PATH: "{{ .Values.serviceMongodb.healthcheckPath }}"
  MONGO_SERVER_SELECTION_TIMEOUT_MS: "{{ .Values.serviceMongodb.serverSelectionTimeout }}"
  MONGO_SOCKET_TIMEOUT_MS: "{{ .Values.serviceMongodb.socketTimeout }}"
  MONGO_MAX_POOL_SIZE: "{{ .Values.serviceMongodb.maxPoolSize }}"
