apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: {{ include "legi-bit.name" . }}
    component: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ include "legi-bit.name" . }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ include "legi-bit.name" . }}
        component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redis.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
