apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mongodb-deployment
  labels:
    app: {{ include "legi-bit.name" . }}
    component: service-mongodb
spec:
  replicas: {{ .Values.serviceMongodb.replicas }}
  selector:
    matchLabels:
      app: {{ include "legi-bit.name" . }}
      component: service-mongodb
  template:
    metadata:
      labels:
        app: {{ include "legi-bit.name" . }}
        component: service-mongodb
    spec:
      serviceAccountName: legibit-sa
      containers:
        - name: service-mongodb
          image: "{{ .Values.serviceMongodb.image.repository }}:{{ .Values.serviceMongodb.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.serviceMongodb.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.serviceMongodb.configMapName }}
            {{- if .Values.serviceMongodb.secretProvider.enabled }}
            - secretRef:
                name: {{ .Values.serviceMongodb.secretProvider.secretName }}
            {{- end }}

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI

          volumeMounts:
            - name: aws-secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true

          resources:
{{ toYaml .Values.serviceMongodb.resources | indent 12 }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.serviceMongodb.port }}
            initialDelaySeconds: 20
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.serviceMongodb.port }}
            initialDelaySeconds: 10
            periodSeconds: 15

      restartPolicy: Always

      {{- if .Values.serviceMongodb.secretProvider.enabled }}
      volumes:
        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mongodb-secrets-provider
      {{- end }}
