apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ses-deployment
  labels:
    app: {{ include "legi-bit.name" . }}
    component: service-ses
spec:
  replicas: {{ .Values.serviceSES.replicas }}
  selector:
    matchLabels:
      app: {{ include "legi-bit.name" . }}
      component: service-ses
  template:
    metadata:
      labels:
        app: {{ include "legi-bit.name" . }}
        component: service-ses
    spec:
      containers:
        - name: service-ses
          image: "{{ .Values.serviceSES.image.repository }}:{{ .Values.serviceSES.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.serviceSES.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.serviceSES.configMapName }}
          
          resources:
{{ toYaml .Values.serviceSES.resources | indent 12 }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.serviceSES.port }}
            initialDelaySeconds: 20
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.serviceSES.port }}
            initialDelaySeconds: 10
            periodSeconds: 15

      restartPolicy: Always
