apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app: {{ include "legi-bit.name" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/load-balancer-name: legibit-alb

    alb.ingress.kubernetes.io/security-groups: sg-009b4bd9f3d3de562
    alb.ingress.kubernetes.io/subnets: '{{ join "," .Values.network.publicSubnets }}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    
    alb.ingress.kubernetes.io/target-group-name: legibit-backend-tg
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type": "redirect", "RedirectConfig":
      {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.acmCertificateArn }}

    alb.ingress.kubernetes.io/healthcheck-path: /alb-health
    alb.ingress.kubernetes.io/success-codes: '200-399'

    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=120,access_logs.s3.enabled=true,access_logs.s3.bucket=legi-bit-alb-logs,access_logs.s3.prefix=alb"

spec:
  ingressClassName: "alb"
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          # Redirect all HTTP traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

          # HEALTH CHECK path (MUST NOT redirect)
          - path: /alb-health
            pathType: Exact
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

    - host: {{ .Values.global.wwwdomain }}
      http:
        paths:
          # Redirect all HTTP traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

          # HEALTH CHECK path (MUST NOT redirect)
          - path: /alb-health
            pathType: Exact
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}