apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: {{ include "legi-bit.name" . }}
    component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "legi-bit.name" . }}
      component: web
  template:
    metadata:
      labels:
        app: {{ include "legi-bit.name" . }}
        component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.web.configMapName }}
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
      restartPolicy: Always
