apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app: {{ include "legi-bit.name" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.acmCertificateArn }}
    alb.ingress.kubernetes.io/healthcheck-path: /alb-health
    alb.ingress.kubernetes.io/success-codes: '200-399'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120

    alb.ingress.kubernetes.io/security-groups: sg-009b4bd9f3d3de562

    alb.ingress.kubernetes.io/subnets: '{{ join "," .Values.network.publicSubnets }}'

    lb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=120,access_logs.s3.enabled=true,access_logs.s3.bucket=legi-bit-alb-logs,access_logs.s3.prefix=alb"

spec:
  ingressClassName: "alb"
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

          # Health של ALB → backend
          - path: /alb-health
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

    - host: {{ .Values.global.wwwdomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

          # Health של ALB → backend
          - path: /alb-health
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}