apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app: {{ include "legi-bit.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Annotations for cert-manager to use Let's Encrypt
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  # TLS configuration
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}

    - http:
        paths:
          - path: /alb-health
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.service.port }}
