apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.web.configMapName }}
data:
  default.conf: |
    server {
      listen 80;

      # ALB/Ingress health endpoint
      location = /alb-health {
        return 200 "ok";
        add_header Content-Type text/plain;
      }

      location / {
        proxy_pass http://{{ .Values.web.backendUrl }};

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        proxy_connect_timeout 5s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
      }
    }
