resources:
  - namespace.yaml
  - aws-ccm-app.yaml
  - configs/configmap-backend.yaml
  - configs/configmap-service-mongodb.yaml
  - configs/configmap-service-s3.yaml
  - configs/configmap-web.yaml
  - deployments/backend-deployment.yaml
  - deployments/redis-deployment.yaml
  - deployments/service-mongodb-deployment.yaml
  - deployments/service-s3-deployment.yaml
  - deployments/web-deployment.yaml
  - services/backend-service.yaml
  - services/redis-service.yaml
  - services/service-mongodb-service.yaml
  - services/service-s3-service.yaml
  - services/web-service.yaml
  - services/web-ingress.yaml
