apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
data:
  MONGODB_SERVER_PORT: "{{ .Values.port }}"
  HEALTHCHECK_PATH: "{{ .Values.healthcheckPath }}"
  MONGO_SERVER_SELECTION_TIMEOUT_MS: "{{ .Values.serverSelectionTimeout }}"
  MONGO_SOCKET_TIMEOUT_MS: "{{ .Values.socketTimeout }}"
  MONGO_MAX_POOL_SIZE: "{{ .Values.maxPoolSize }}"
