# legibit/charts/ses/values.yaml
image:
  repository: webserver0518/legi-bit-ses
  tag: "v0.3"
  pullPolicy: IfNotPresent

port: 8002
replicas: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

host: "service-ses"

configMapName: "service-ses-config"
healthcheckPath: "/healthz"

serviceName: "ses"
service:
  type: ClusterIP
  port: 8002
