# legibit/values.yaml  (ROOT / UMBRELLA)
global:
  imagePullPolicy: IfNotPresent
  domain: legi-bit.com
  wwwdomain: www.legi-bit.com

  services:
    redis:
      host: redis
      port: 6379
      db: "0"
    s3:
      host: s3
      port: 8000
    mongodb:
      host: mongodb
      port: 8001
    ses:
      host: ses
      port: 8002

network:
  publicSubnets:
    - subnet-0a044c1a78eebf032
    - subnet-0f567de7dfc506182
    - subnet-007e9c39120d90a5d

ingress:
  name: "legibit-ingress"
  acmCertificateArn: "arn:aws:acm:eu-north-1:780180237362:certificate/104562a5-1c06-4008-8af2-c790775c1907"
  lbAttributes: "idle_timeout.timeout_seconds=120,access_logs.s3.enabled=true,access_logs.s3.bucket=legi-bit-alb-logs,access_logs.s3.prefix=alb"

https:
  email: webserver0518@gmail.com

monitoring:
  enabled: true

web:
  enabled: true

backend:
  enabled: true

mongodb:
  enabled: true

s3:
  enabled: true

ses:
  enabled: true

redis:
  enabled: true
