apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "redis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: tcp
              containerPort: {{ .Values.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
