apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ include "web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
