apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  labels:
    app: cloudflared
data:
  config.yaml: |
    tunnel: {{ required "A valid tunnel token is required!" .Values.secret.name | quote }}
    ingress:
{{ toYaml .Values.config.ingress | indent 6 }}
