# legibit/values.yaml  (ROOT / UMBRELLA)
global:
  imagePullPolicy: IfNotPresent
  domain: legi-bit.com
  wwwdomain: www.legi-bit.com

  services:
    redis:
      host: redis
      port: 6379
      db: "0"
    s3:
      host: s3
      port: 8000
    mongodb:
      host: mongodb
      port: 8001
    ses:
      host: ses
      port: 8002

  monitoring:
    enabled: true


https:
  email: webserver0518@gmail.com


web:
  enabled: true

backend:
  enabled: true

mongodb:
  enabled: true

s3:
  enabled: true

ses:
  enabled: true

redis:
  enabled: true
