apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    app.kubernetes.io/name: {{ include "ses.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ses
data:
  SES_SERVER_PORT: "{{ .Values.port }}"
  HEALTHCHECK_PATH: "{{ .Values.healthcheckPath }}"
  MAX_UPLOAD_SIZE_MB: "{{ .Values.maxUploadSizeMb }}"
