apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ses.fullname" . }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "ses.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ses
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ses.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ses
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ses.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ses
    spec:
      containers:
        - name: ses
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: 20
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 15

      restartPolicy: Always
