apiVersion: v1
kind: ConfigMap
metadata:
  name: service-s3-config
  namespace: legibit
  labels:
    app: legibit
    component: service-s3
data:
  S3_SERVER_PORT: "8000"
  HEALTHCHECK_PATH: "/healthz"
  MAX_UPLOAD_SIZE_MB: "50"