apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: legibit
  labels:
    app: legibit
    component:  backend
data:
  # Flask
  FLASK_SERVER_PORT: "9000"
  FLASK_ENV: "development"
  # flask signature
  SECRET_KEY: "dfb594091faa05005d1212f4cdce9dc64a81c9ff50253210520375a9fd25a934"
  
  # Redis
  SESSION_TYPE: "redis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  SESSION_REDIS_URL: "redis://redis:6379/0"
  
  # Services URL
  S3_SERVICE_URL: "http://service-s3:8000"
  MONGODB_SERVICE_URL: "http://service-mongodb:8001"
