apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: legibit
  labels:
    app: legibit
    component: backend
data:
  FLASK_SERVER_PORT: "9091"
  FLASK_ENV: "development"
  LIMITER_DEFAULT: "50 per hour"
  LIMITER_LOGIN: "5 per minute"