apiVersion: v1
kind: ConfigMap
metadata:
  name: service-mongodb-config
  namespace: legibit
  labels:
    app: legibit
    component: service-mongodb
data:
  MONGODB_SERVER_PORT: "8001"
  HEALTHCHECK_PATH: "/healthz"
  MONGO_SERVER_SELECTION_TIMEOUT_MS: "5000"
  MONGO_SOCKET_TIMEOUT_MS: "10000"
  MONGO_MAX_POOL_SIZE: "100"
